### ISSUE TITLE
SQL: RPC interface

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#1014]
**Problem**

We want a flexible RPC interface for librillsql that allows us to easily pass complex objects across language barriers and makes it easy to keep the bindings in sync. Ideally, the solution also enables the SQL library to make callbacks to the client to execute catalog lookups (instead of passing in the full catalog on every call).

**Solution**

We can use protocol buffers to express an RPC interface for `librillsql`. It would have several advantages:

- It would allow us to easily generate bindings for many languages
- It will allow us to add new functionality without modifying the C entrypoints – just modify and re-generate the protocol buffer definitions
- It will interoperate nicely with our existing protobuf-based ASTs ([link](https://github.com/rilldata/rill-developer/blob/main/sql/src/main/java/com/rilldata/protobuf/SqlNodeProto.proto))

**Resources**

Protobufs are widely used for RPCs. Some especially relevant prior art:

- Hashicorp uses gRPC for in-process plugins: https://github.com/hashicorp/go-plugin
- `libpg_query` uses protobufs to represent Postgres ASTs ([core library](https://github.com/pganalyze/libpg_query), [Go bindings](https://github.com/pganalyze/pg_query_go))
- Avatica uses protobufs for their binary format: https://calcite.apache.org/avatica/docs/protobuf_reference.html

Also see our [Notion discussion](https://www.notion.so/rilldata/SQL-implementation-81431cebe85840e8ae25d3e182c40dec#f279fffff9024882a83faa74de1045ab
) of entrypoints for `librillsql`.

**Prototype**

Here's a quick prototype for what a protobuf-based RPC for `librillsql` could look like. Note that it was put together quickly and will likely need to be significantly adapted. 

It introduces a notion of a callback for catalog lookups. This prevents passing the full catalog on every invocation. The sequencing would look something like this:

1. Go calls into `librillsql` by passing a serialized `Request` and a callback function.
2. During execution, `librillsql` calls the callback function with zero or more `CallbackRequest`, and receives corresponding `CallbackResponse`s from Go.
3. Eventually, `librillsql` returns on the original call with a `Response` object.

The C bindings could look something like this:

```c
// Represents a serialized protocol buffer message 
struct buffer {
  void* message;
  size_t length;
};

// Calls librillsql by passing in a serialized Request and returns a serialized Response.
// The callback is a function that takes a serialized CallbackRequest and returns a serialized CallbackResponse.
// Its signature would be something like: struct buffer callback(struct buffer callback_request)
struct buffer call(struct buffer request, void* callback_func);
```

Here's a prototype protocol buffer representation:

```proto
syntax = "proto3";

package sql.v1;

// *******************************
// RPC for calling into librillsql
// *******************************

enum Dialect {
    DIALECT_DRUID = 0;
    DIALECT_DUCKDB = 1;
}

message Request {
    oneof request {
        ParseRequest parse_request = 1;
        UnparseRequest unparse_request = 2;
        TranspileRequest transpile_request = 3;
        ApplyRequest apply_request = 4;
    }
}

message Response {
    oneof response {
        ParseResponse parse_response = 1;
        UnparseResponse unparse_response = 2;
        TranspileResponse transpile_response = 3;
        ApplyResponse apply_response = 4;
    }
}

message ParseRequest {
    string sql = 1;
}

message ParseResponse {
    // Should import and use sql/src/main/java/com/rilldata/protobuf.SqlNodeProto
    SqlNodeProto ast = 1;
    string error = 2;
}

message UnparseRequest {
    SqlNodeProto ast = 1;
}

message UnparseResponse {
    string sql = 1;
    string error = 2;
}

message TranspileRequest {
    string sql = 1;
    Dialect dialect = 2;
}

message TranspileResponse {
    string sql = 1;
    string error = 2;
}

message ApplyRequest {
    message File {
        string path = 1;
        string blob = 2; // contains multiple SQL statements
    }
    repeated File files = 1;
}

message ApplyResponse {
    // ...
    string error = 2;
}

// *******************************
// RPC for librillsql callbacks
// *******************************

message CallbackRequest {
    oneof request {
        CatalogRequest catalog_request = 1;
    }
}

message CallbackRequest {
    oneof request {
        CatalogResponse catalog_response = 1;
    }
}

message CatalogRequest {
    // Object names to lookup in catalog
    repeated string name = 1;
}

message CatalogResponse {
    // Objects found 
    repeated SqlNodeProto objects = 1; // Probably not the right type?
}
```

**Questions**

- How do we pass errors? The prototype adds error handling to the individual response messages, but maybe they better belong in the root `Response` message?
- Would it make sense to use gRPC instead of basic protobufs? gRPC has a bi-directional streaming concept, which could be used for catalog lookups. But on the other hand, gRPC is designed for communication over networks/sockets and is more complicated than the above design.
- What types should we use for catalog objects? We could pass protobuf AST nodes, but we won't always have that available (e.g. for existing tables we discover in the DB's information schema). Does Calcite have a schema type available we can adapt for use in protobufs? Otherwise, we can probably roll one ourselves. 

**Tasks**

- [ ] Prepare build scripts that will compile .proto definition files and output sources for Runtime and Sql subprojects.
- [ ] Implement ParseRequest/ParseResponse processing
- [ ] Implement Runtime-side schema generation (required for the following task)
- [ ] Implement CallbackRequest/CallbackResponse processing

**Comment by begelundmuller** [comment]
I did some research on how to represent schema types using protobufs and found these instructive:

- https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/type.proto
- https://calcite.apache.org/avatica/docs/protobuf_reference.html#columnmetadata

**Comment by nishantmonu51** [comment]
Overall a solid proposal. 
My 2 cents - 
1. I would not expect the catalogs to be too large to begin with. Performance wise it would be fine serialize and pass the full catalog to the library as well and bypass the complexity of callbacks. The work for serializing a catalog can be reused when we reach the optimization stage. 
2. Error handling - agreed, would be nice to have it belong to root response object
