### ISSUE TITLE
Code Quality - Testing Suite

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill#227]
**Initiative**
Our testing suite is not performing reliably and we need to clean up the code to increase it's utility during development.

**Checklist of Issues**
- [ ] [investigate the non-deterministic test failures](https://github.com/rilldata/rill-developer/issues/224)
- [ ] [Test suite returns a large number of console.error calls](https://github.com/rilldata/rill-developer/issues/202)
- [ ] [the EntityStatus.spec.ts tests appear to be non-deterministic and are failing more often than not](https://github.com/rilldata/rill-developer/issues/207)

**Comment by hamilton** [comment]
Some pre-work has been done here: https://github.com/rilldata/rill-developer/pull/117

**Comment by bcolloran** [comment]
#243 comments out a few of these for now
