### ISSUE TITLE
Frontend meta

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#2288]
## Backlog

- [ ] #3180 (@AdityaHegde)
- [ ] #3257 (@djbarnwal)
- [ ] Custom Time Range not working for underlying Date type ([Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1696606952689089))

### Performance

- [ ] Timeseries charts need a loading/stale state when subsequent queries take a while
- [ ] Add performance tests

### Stability

- [ ] Catch application errors in an error boundary and emit telemetry. Also, use the Rill Cloud error page in Rill Developer. See: https://github.com/sveltejs/rfcs/pull/46#issuecomment-1642733231
- [ ] Dashboard should be responsive to smaller screen sizes
- [ ] Add an error page to Rill Developer when not connected to the runtime
- [ ] web e2e tests should propagate runtime logs
- [ ] Line chart animation gets stuck in a loop ([Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1696408214297229)) 
- [ ] https://github.com/rilldata/rill/issues/2949
- [ ] Empty `Select` expression when querying Druid (@AdityaHegde, [Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1686735159020519))
- [ ] Removing a Metric Def's time column, then navigating back to the dashboard triggers a couple 400 errors. When removing the time column, we should clear `dashboardStore.selectedTimeRange`. ([Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1687897279428449?thread_ts=1687812338.356339&cid=C02T907FEUB))
- [ ] In the Cloud UI, when deleting a project from the CLI, a 404 page pops up – even when you're not on the said project page ([Slack](https://rilldata.slack.com/archives/C0415QK8DK6/p1689777541484999))
- [ ] When loading the application with remote sources that have errors (like credentials errors), the Error console does not show an error until clicking the "Refresh" button
- [ ] In Rill Developer, there are several pages of whitespace below the toplists ([Slack](https://rilldata.slack.com/archives/C02T907FEUB/p1687424313118119))
- [ ] Logging out on the `/-/auth/device` page shows a `null` code ([Slack discussion](https://rilldata.slack.com/archives/CTZ8XBQ85/p1685945608139469), [another instance reported in Slack](https://rilldata.slack.com/archives/CTZ8XBQ85/p1705513088051579))
- [ ] https://github.com/rilldata/rill-developer/issues/1916
- [ ] Fix all the 400 errors that show in the browser console
- [ ] Add to the error page a "developer" section with informative error details

### State management
- [ ] Navigating to a dashboard should apply the last seen filter state
- [x] https://github.com/rilldata/rill/issues/2703
- [ ] TanStack: Use different QueryClients for the Admin server and each Runtime server
- [ ] TanStack: Use the `enabled` flag for all dependent queries in `web-common`
- [ ] TanStack: Simplify query invalidation (try to use `invalidateQueries` everywhere, solve the apparent bugs)

### Design
- [ ] Ability to navigate to a URL that's a dimension value
- [ ] Delay certain loading spinners by 200-500ms so they don't flash
- [ ] Add more context to the "Last" time range option
- [ ] The Dashboard YAML editor's "Find" menu is somewhat offscreen when editing a full page file
- [ ] Put loading spinners in timeseries charts in the middle, not in the top left 
- [ ] Fix unstyled font flash on the auth page
- [ ] Standardize menus
- [ ] Consider the `tailwind-merge` library ([docs](https://github.com/dcastil/tailwind-merge/blob/v1.13.2/docs/when-and-how-to-use-it.md))
- [ ] Add `aria-label` to our interactive elements going forward

### Miscelleaneous
- [ ] https://github.com/rilldata/rill-developer/issues/2410
- [ ] Feature flags at scale
- [ ] Avoid long relative imports. Use absolute paths, SvelteKit aliases, or different VSCode settings
- [ ] Adopt an established style guide and leverage its corresponding `eslint` configuration
