### ISSUE TITLE
Scheduled Reports UI follow-ups

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#3427]
The core of Scheduled Reports is now on `main`. Here's a running list of follow-on work:
- [x] [Blocker] Add a docs page (@mindspank)
- [x] [Blocker] Send the correct time range and comparison time range. Dependent on #3417 (@AdityaHegde, https://github.com/rilldata/rill/pull/3455)
- [x] [Blocker] Allow any email to be added as a recipient (@ericpgreen2, https://github.com/rilldata/rill/pull/3444)
- [x] [Blocker] Fix time zone bug & add ability to specify a non-local time zone for the report (@ericpgreen2, https://github.com/rilldata/rill/pull/3459)
- [x] [Blocker] Fix 403 error on reports page when user isn't an admin of the project (@ericpgreen2, #3470, #3469)
- [x] Add UI to the `/-/reports/{reportName}/export` page (@AdityaHegde)
- [x] Improve design of the Report page's metadata section (e.g. emphasize the Next Run On date; show the recipients) (@jkhwu)
- [x] Implement new design of Report page's metadata (@ericpgreen2, #3469)
- [x] Revise the "Recipients" form element (@ericpgreen2, https://github.com/rilldata/rill/pull/3500)
- [x] Form should default to your local time zone (@ericpgreen2, https://github.com/rilldata/rill/pull/3502)
- [x] Edit CTA when 0 reports in a project (@ericpgreen2, https://github.com/rilldata/rill/pull/3503)
- [x] Add an "Edit" button to the Report page (@ericpgreen2, https://github.com/rilldata/rill/pull/3505)
- [x] Add a "Run now" primary button to the report page (@ericpgreen2, https://github.com/rilldata/rill/pull/3540)
- [x] Upon report creation, use a persistent toast w/ link to the report page (@ericpgreen2, https://github.com/rilldata/rill/pull/3558)
- [x] Hide the “delete/edit report” button if the report is created through code. (@ericpgreen2, #3563)
- [x] Sometimes editing a report makes it appear deleted due to a parsing error “invalid time zone: unknown time zone PST”. (@ericpgreen2, #3581)

**Comment by nishantmonu51** [comment]
Adding link to notion - https://www.notion.so/rilldata/Finish-implementing-report-actions-edit-unsubscribe-etc-721a98c188044ed0a131d719ee202706?pvs=4
