### ISSUE TITLE
Alerts UI burndown list

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill#4115]
## Future work
- When creating an alert, it's checked immediately. Is that intended? ([Discussion here](https://rilldata.slack.com/archives/C06638A72TH/p1708941515301819?thread_ts=1708709117.990789&cid=C06638A72TH))
- Include measure filters when providing the alert input data. To ensure correct data, a refactor is needed: move measure filter resolution from frontend to backend.
- Alert on contextual columns, like % change.
- Combine the Data and Criteria tabs?
- Add a global entrypoint for alerts?
- "Are you sure you want to cancel?" dialog (https://github.com/rilldata/rill/pull/4140)
- Measure multi-select
- Alert detail page: make the Snooze configurable with a simple dropdown

Design polish
- Sort the Data / Alert preview by the measure in descending order
- Data Preview width should always fill available space
- Options in the Select element should extend the full width of the element
- Our button component doesn't appear to exactly center text vertically
- In Alert Detail page's metadata section, we should capitalize the first letter of the "Split by dimension" dimension name

## Completed
- [x] Switching to the Criteria tab triggers a 400 error from the `Aggregation` API
- [x] Split by dimension/time should include a "None" option (#4187)
- [x] "Edit alert" button and dialog (https://github.com/rilldata/rill/pull/4139)
- [x] Change alert status backend-to-frontend mapping to match spec ([Slack convo](https://rilldata.slack.com/archives/C06638A72TH/p1708711554285299)) (https://github.com/rilldata/rill/pull/4195)
- [x] Add explanation for why an Alert check "Failed" (https://github.com/rilldata/rill/pull/4195)
- [x] The below criteria should read "New vaccinations > 200" (#4187)
![image](https://github.com/rilldata/rill/assets/14206386/d507cd8e-681c-460c-85f5-384ccd9cdba5)
- [x] Clicking on an email's "Open in browser" link leads to this bad URL: `http://localhost:3000/rilldata/rill-test-covid/-/alerts/MetricsViewAggregation` (#4161)
- [x] Clicking a new alert led to a 404 page (Issue not specific to alerts, #4206)
- [x] Creating with empty filters fails the backend query. (#4205)
- [x] Split by grain is not filled in while editing an alert. (#4205)
- [x] Show form validation errors everywhere. They should be triggered by attempting to advance to the next page (button shouldn't be disabled). (#4210)
- [x] In the Criteria tab, when the form isn't complete, we need proper copy for the empty Alert Preview section (https://github.com/rilldata/rill/pull/4217)
- [x] Fix the time range provided to the query in the Create Alert API (#4240)
- [x] Include a time range indication in the filters section (#4240)
- [x] Move the "Split by time grain" section to the Delivery tab and call it "Evaluation interval". [Discussion here](https://rilldata.slack.com/archives/C06638A72TH/p1709254991171789). (#4240)
- [x] Exclude dimension filters are displayed as include filters. (#4240)

**Comment by medriscoll** [comment]
Thanks Eric, per your comment around proper formatting of percentages in the preview modal, this is what I currently see... also of interest, I'd ideally like to have it mirror the sort order of the expanded dimension table.

A second issue that is evident here is that the bottom of the modal is not visible at my screen size resolution, so I can't see the 'Next' and 'Cancel' calls to action unless I scroll down. 

![image](https://github.com/rilldata/rill/assets/306103/576ebb00-e988-4569-8446-365c048a22f3)
