### ISSUE TITLE
Runtime: Advanced measures follow-up

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill#5021]
**Tasks remaining:**

- [x] Sort with `NULLS LAST`
- [x] Use `IS NOT DISTINCT FROM` for joins
- [x] Apply a default execution timeout to queries in `Executor`
- [x] Ensure limits are always applied, including in the resolver
- [x] Optimizer for approximate comparisons
- [x] Optimizer for limit/sort pushdown
- [x] Optimizer for Druid exactify
- [x] Support `pivot_on`
- [x] Optimized exports
